### ISSUE TITLE
Change an image

### ISSUE THREAD

**Issue by sdsubhajitdas** [karmakarivan/codehub.io#14]
Change the image of "Displaying the Result".
We had a talk about it that we will change the mobile screen to app's screen u have the app so start changing it.
Ohh and use my profile screen shot and put that on the mobile screen.

**Comment by karmakarivan** [comment]
karmakarivan.github.io/codehub.io 
Check kor bnara.. sob hoye gache .. even Tor video r o... Bnara

**Comment by sdsubhajitdas** [comment]
Niceeeeee sassskkkyyyy bnaraaa
